DROP TABLE IKASLEAK;
DROP TABLE IKASTAROAK;
DROP TABLE IRAKASLEAK;

CREATE TABLE IKASLEAK (
	IZENA VARCHAR(25) NOT NULL,
    ABIZENA1 VARCHAR(25) NOT NULL,
    ABIZENA2 VARCHAR(25),
    IFZ INT PRIMARY KEY,
    HELBIDEA VARCHAR(255), 
    SEXUA CHAR(1) NOT NULL, 
    JAIOTZE_DATA DATE NOT NULL,
    MAILA VARCHAR(50),
    CONSTRAINT CK_SEXU CHECK (SEXUA IN ('M', 'F', 'B')) 
);

CREATE TABLE IRAKASLEAK (
	IZENA VARCHAR(25) NOT NULL, 
    ABIZENA1 VARCHAR(25) NOT NULL,
    ABIZENA2 VARCHAR(25),
    IFZ INT PRIMARY KEY,
    HELBIDEA VARCHAR(255), 
    TITULAZIOA VARCHAR(25),
    SOLDATA DOUBLE,
    UNIQUE (IZENA, ABIZENA1, ABIZENA2)
);

CREATE TABLE IKASTAROAK (
	IZENA VARCHAR(25) NOT NULL UNIQUE,
	KODEA INT PRIMARY KEY,
    IRAKASLE_IFZ INT,
    IKASLE_KOPURU INT,
    HASIERA_DATA DATE NOT NULL,
    AMAIERA_DATA DATE NOT NULL,
    ORDU_KOPURU INT NOT NULL,
    CONSTRAINT FK_IRAKASLEAK_IKASTAROAK FOREIGN KEY(IRAKASLE_IFZ) REFERENCES IRAKASLEAK(IFZ),
    CONSTRAINT CK_ORDU CHECK (ORDU_KOPURU > 0),
    CONSTRAINT CK_DATAK CHECK (HASIERA_DATA <= AMAIERA_DATA)
);

/*ALDAKETAK*/
ALTER TABLE IKASLEAK ADD ADINA INT;
ALTER TABLE IKASLEAK ADD CONSTRAINT CK_URTEAK CHECK(ADINA BETWEEN 14 AND 65);
ALTER TABLE IKASTAROAK ADD CONSTRAINT CK_ORDUAK CHECK(ORDU_KOPURU IN (30, 40, 60)); 
ALTER TABLE IKASTAROAK ADD CONSTRAINT CK_LIMITEAK CHECK(IKASLE_KOPURU >= 15);
ALTER TABLE IKASLEAK DROP CONSTRAINT CK_SEXU;
ALTER TABLE IRAKASLEAK DROP COLUMN HELBIDEA;
ALTER TABLE IKASTAROAK DROP FOREIGN KEY FK_IRAKASLEAK_IKASTAROAK;
ALTER TABLE IRAKASLEAK DROP PRIMARY KEY;
ALTER TABLE IRAKASLEAK ADD PRIMARY KEY (IZENA, ABIZENA1, ABIZENA2);
ALTER TABLE IRAKASLEAK RENAME TUTOREAK;

