/*BEZERO eta BEZERO_TELEFONO informazioa:*/
CREATE OR REPLACE VIEW BEZERO_INFO AS
SELECT BEZERO.ID, CONCAT_WS(' ', BEZERO.IZENA, BEZERO.ABIZENA) AS IZENA, BEZERO.HELBIDEA, BEZERO.EMAILA, BEZERO_TELEFONO.ZENBAKIA 
FROM BEZERO 
INNER JOIN BEZERO_TELEFONO ON BEZERO.ID = BEZERO_TELEFONO.ID_BEZERO;

/*BILTEGI, KOKALEKU, HERRIALDE ETA KONTINENTE TAULA informazioa*/
CREATE OR REPLACE VIEW BILTEGI_INFO AS
SELECT BILTEGI.ID, BILTEGI.IZENA, KOKALEKU.HELBIDEA, KOKALEKU.POSTAKODEA, KOKALEKU.UDALERRIA, KOKALEKU.PROBINTZIA, KOKALEKU.ID_HERRIALDE,
HERRIALDE.IZENA AS HERRIALDE, KONTINENTE.IZENA AS KONTINENTE
FROM BILTEGI 
INNER JOIN KOKALEKU ON BILTEGI.ID_KOKALEKU = KOKALEKU.ID
INNER JOIN HERRIALDE ON KOKALEKU.ID_HERRIALDE = HERRIALDE.ID
INNER JOIN KONTINENTE ON HERRIALDE.ID_KONTINENTE = KONTINENTE.ID;

/*PRODUKTU, KATEGORIA, ESKARI_LERRO, ESKARI, ESKARI_EGOERA, BEZERO, SALTZAILE, LANGILE, INBENTARIOA eta BILTEGI informazioa*/
CREATE OR REPLACE VIEW PRODUKTU_INFO AS
SELECT DISTINCT PRODUKTU.ID, PRODUKTU.IZENA AS PRODUKTU_IZENA, PRODUKTU.DESKRIBAPENA, PRODUKTU.BALIOA, ESKARI_LERRO.SALNEURRIA, 
KATEGORIA.IZENA AS KATEGORIA_IZENA, ESKARI_LERRO.KOPURUA,
ESKARI.ESKAERA_DATA, ESKARI_EGOERA.DESKRIBAPENA AS ESKAERA_EGOERA,
CONCAT_WS(' ', BEZERO.IZENA, BEZERO.ABIZENA) AS BEZERO_IZENA, BEZERO.EMAILA AS BEZERO_EMAILA,
CONCAT_WS(' ', LANGILE.IZENA, LANGILE.ABIZENA) AS SALTZAILE_IZENA, SALTZAILE.ERABILTZAILEA AS SALTZAILEA, LANGILE.EMAILA AS LANGILE_EMAILA,
INBENTARIO.KOPURUA AS PRODUKTU_KOPURUA, BILTEGI.IZENA AS BILTEGI_IZENA
FROM PRODUKTU 
INNER JOIN KATEGORIA ON PRODUKTU.ID_KATEGORIA = KATEGORIA.ID
INNER JOIN ESKARI_LERRO ON PRODUKTU.ID = ESKARI_LERRO.ID_PRODUKTU
INNER JOIN ESKARI ON ESKARI_LERRO.ID_ESKARI = ESKARI.ID
INNER JOIN ESKARI_EGOERA ON ESKARI.ID_EGOERA = ESKARI_EGOERA.ID
INNER JOIN BEZERO ON ESKARI.ID_BEZERO = BEZERO.ID
INNER JOIN SALTZAILE ON ESKARI.ID_SALTZAILE = SALTZAILE.ID 
INNER JOIN LANGILE ON SALTZAILE.ID = LANGILE.ID
INNER JOIN INBENTARIO ON PRODUKTU.ID = INBENTARIO.ID_PRODUKTU
INNER JOIN BILTEGI ON INBENTARIO.ID_BILTEGI = BILTEGI.ID
ORDER BY PRODUKTU.ID ASC;

/* LANGILE, SALTZAILE eta BULEGARI informazioa*/
CREATE OR REPLACE VIEW LANGILE_INFO AS
SELECT LANGILE.ID, CONCAT_WS(' ', LANGILE.IZENA, LANGILE.ABIZENA) AS IZEN_ABIZENAK, SALTZAILE.ERABILTZAILEA, SALTZAILE.PASAHITZA,
LANGILE.EMAILA, LANGILE.TELEFONOA, LANGILE.KONTRATAZIO_DATA, LANGILE.ID_NAGUSI, LANGILE.SOLDATA, LANPOSTU.DESKRIBAPENA AS LANPOSTUA
FROM LANGILE
LEFT JOIN SALTZAILE ON LANGILE.ID = SALTZAILE.ID
LEFT JOIN BULEGARI ON LANGILE.ID = BULEGARI.ID
LEFT JOIN LANPOSTU ON BULEGARI.ID_LANPOSTU = LANPOSTU.ID;

/*ERABILTZAILEAK informazioa*/
CREATE OR REPLACE VIEW ERABILTZAILE_INFO AS
SELECT * FROM ERABILTZAILEAK;

/*KONTSULTAK*/
SELECT * FROM ERABILTZAILE_INFO;
SELECT * FROM BEZERO_INFO;
SELECT * FROM BILTEGI_INFO;
SELECT * FROM PRODUKTU_INFO;
SELECT * FROM LANGILE_INFO;
